//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.HotelService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelData", Namespace="http://schemas.datacontract.org/2004/07/Hotels")]
    [System.SerializableAttribute()]
    public partial class HotelData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelRatingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelAddress {
            get {
                return this.HotelAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelAddressField, value) != true)) {
                    this.HotelAddressField = value;
                    this.RaisePropertyChanged("HotelAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((this.HotelIdField.Equals(value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelName {
            get {
                return this.HotelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelNameField, value) != true)) {
                    this.HotelNameField = value;
                    this.RaisePropertyChanged("HotelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelRatings {
            get {
                return this.HotelRatingsField;
            }
            set {
                if ((this.HotelRatingsField.Equals(value) != true)) {
                    this.HotelRatingsField = value;
                    this.RaisePropertyChanged("HotelRatings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelService.IHotel")]
    public interface IHotel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetHotelData", ReplyAction="http://tempuri.org/IHotel/GetHotelDataResponse")]
        Client.HotelService.HotelData[] GetHotelData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetHotelData", ReplyAction="http://tempuri.org/IHotel/GetHotelDataResponse")]
        System.Threading.Tasks.Task<Client.HotelService.HotelData[]> GetHotelDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetHotelById", ReplyAction="http://tempuri.org/IHotel/GetHotelByIdResponse")]
        Client.HotelService.HotelData GetHotelById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetHotelById", ReplyAction="http://tempuri.org/IHotel/GetHotelByIdResponse")]
        System.Threading.Tasks.Task<Client.HotelService.HotelData> GetHotelByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelChannel : Client.HotelService.IHotel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelClient : System.ServiceModel.ClientBase<Client.HotelService.IHotel>, Client.HotelService.IHotel {
        
        public HotelClient() {
        }
        
        public HotelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.HotelService.HotelData[] GetHotelData() {
            return base.Channel.GetHotelData();
        }
        
        public System.Threading.Tasks.Task<Client.HotelService.HotelData[]> GetHotelDataAsync() {
            return base.Channel.GetHotelDataAsync();
        }
        
        public Client.HotelService.HotelData GetHotelById(int id) {
            return base.Channel.GetHotelById(id);
        }
        
        public System.Threading.Tasks.Task<Client.HotelService.HotelData> GetHotelByIdAsync(int id) {
            return base.Channel.GetHotelByIdAsync(id);
        }
    }
}
